version: '3'

services:
  word-of-wisdom-server:
    build:
      context: ./
      dockerfile: cmd/server/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - wisdom-network

  word-of-wisdom-client:
    build:
      context: ./
      dockerfile: cmd/client/Dockerfile
    networks:
      - wisdom-network
    depends_on:
      - word-of-wisdom-server

networks:
  wisdom-network:
    driver: bridge